default:
  project_type: project

  # Core directories (inline for discoverability)
  directories:
    notebooks: notebooks
    scripts: scripts
    functions: functions
    results_public: results/public
    results_private: results/private
    cache: data/cached
    scratch: data/scratch

  # Domain-specific settings (split files for scalability)
  data: settings/data.yml
  packages: settings/packages.yml
  connections: settings/connections.yml
  git: settings/git.yml
  security: settings/security.yml
