default:
  # --------------------------------------------------------------------------
  # Project Metadata
  # --------------------------------------------------------------------------
  project_type: project  # Type: project, course, or presentation

  # Project author information (used in notebooks, reports, etc.)
  author:
    name: "Your Name"
    email: "your.email@example.com"
    affiliation: "Your Institution"

  # --------------------------------------------------------------------------
  # Package Dependencies
  # --------------------------------------------------------------------------
  # Packages to install and optionally auto-load during scaffold()
  # Use auto_attach: true to load automatically, false to install only
  # Version pinning: dplyr@1.1.0, user/repo@branch
  # --------------------------------------------------------------------------
  packages: settings/packages.yml  # Split file for package configuration

  # --------------------------------------------------------------------------
  # Project Directories
  # --------------------------------------------------------------------------
  # Define the core directory structure for your project.
  # Most users can leave these as defaults.
  # All paths are relative to the project root.
  # --------------------------------------------------------------------------
  directories:
    # Source code and notebooks
    notebooks: notebooks          # Where make_notebook() creates files
    scripts: scripts              # Where make_script() creates files
    functions: functions          # Single dir or list: [functions, helpers]

    # Analysis outputs
    results_public: results/public    # Shareable outputs (plots, reports)
    results_private: results/private  # Private outputs (internal reports)

    # Data and caching
    cache: data/cached            # Cached computation results
    scratch: data/scratch         # Temporary workspace

  # --------------------------------------------------------------------------
  # Project Behavior
  # --------------------------------------------------------------------------
  # Default notebook format for make_notebook() (quarto or rmarkdown)
  default_notebook_format: quarto

  # Random seed for reproducibility
  # Set during scaffold() to ensure consistent random operations
  # Use YYYYMMDD format (e.g., 20241016) or any integer
  # Set to null to disable automatic seeding
  # Falls back to global ~/.frameworkrc FW_SEED if not specified
  seed: 20241016

  # --------------------------------------------------------------------------
  # Data Catalog
  # --------------------------------------------------------------------------
  # Simple approach: Define data sources inline
  # Complex projects: Use split file (data: settings/data.yml)
  # --------------------------------------------------------------------------
  data: settings/data.yml  # Data catalog lives in settings/data.yml

  # --------------------------------------------------------------------------
  # Database Connections
  # --------------------------------------------------------------------------
  # Simple approach: Define connections inline
  # Complex projects: Use split file (connections: settings/connections.yml)
  #
  # ⚠️ PRECEDENCE RULE: Main settings file ALWAYS wins
  # If you define 'default_connection' here AND in settings/connections.yml,
  # the value here takes precedence. Framework will warn about the conflict.
  # --------------------------------------------------------------------------
  connections: settings/connections.yml  # Database connections split file

  # Security settings
  security: settings/security.yml  # Encryption keys and policies

  # --------------------------------------------------------------------------
  # AI Assistant Configuration
  # --------------------------------------------------------------------------
  ai:
    canonical_file: ""

  # --------------------------------------------------------------------------
  # Git Hooks
  # --------------------------------------------------------------------------
  git: settings/git.yml  # Git settings (hooks, remotes)
