default:
  project_type: course

  # Instructor information (used in course materials, notebooks, etc.)
  author:
    name: "Instructor Name"
    email: "instructor@university.edu"
    affiliation: "University Name"

  # Core directories
  directories:
    notebooks: notebooks
    presentations: presentations
    functions: functions
    cache: data/cached

  # Project behavior
  default_notebook_format: quarto  # quarto or rmarkdown
  renv_nag: true

  # Domain-specific settings (split files for scalability)
  data: settings/data.yml
  packages: settings/packages.yml
  connections: settings/connections.yml
  git: settings/git.yml
  security: settings/security.yml
