test_that("project root _quarto.yml is generated with HTML defaults", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_quarto")

  result <- project_create(
    name = "test_quarto",
    location = project_path,
    type = "project",
    quarto = list(
      html = list(
        embed_resources = TRUE,
        theme = "cosmo",
        toc = TRUE,
        toc_depth = 3,
        code_fold = FALSE,
        code_tools = FALSE,
        highlight_style = "github"
      )
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check _quarto.yml exists at project root
  quarto_path <- file.path(result$path, "_quarto.yml")
  expect_true(file.exists(quarto_path))

  # Read and validate _quarto.yml
  quarto <- yaml::read_yaml(quarto_path)
  expect_equal(quarto$format$html$theme, "cosmo")
  expect_true(quarto$format$html$toc)
  expect_equal(quarto$format$html$`toc-depth`, 3)
  expect_true(quarto$format$html$`embed-resources`)
  expect_equal(quarto$format$html$`highlight-style`, "github")

  # Check auto-generated header comment
  lines <- readLines(quarto_path)
  expect_true(any(grepl("Auto-generated by Framework", lines[1:3])))
  expect_true(any(grepl("yours to customize", lines[1:3])))
})

test_that("standard project generates _quarto.yml in render directories", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_project_renders")

  result <- project_create(
    name = "test_project_renders",
    location = project_path,
    type = "project",
    render_dirs = list(
      notebooks = "outputs/notebooks",
      docs = "outputs/docs"
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check _quarto.yml in notebooks render directory
  notebooks_quarto <- file.path(result$path, "outputs/notebooks/_quarto.yml")
  expect_true(file.exists(notebooks_quarto))
  notebooks_config <- yaml::read_yaml(notebooks_quarto)
  expect_equal(notebooks_config$format$html$theme, "default")

  # Check _quarto.yml in docs render directory
  docs_quarto <- file.path(result$path, "outputs/docs/_quarto.yml")
  expect_true(file.exists(docs_quarto))
  docs_config <- yaml::read_yaml(docs_quarto)
  expect_equal(docs_config$format$html$theme, "default")
})

test_that("course project generates _quarto.yml in correct render directories", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_course")

  result <- project_create(
    name = "test_course",
    location = project_path,
    type = "course",
    render_dirs = list(
      slides = "rendered/slides",
      assignments = "rendered/assignments",
      course_docs = "rendered/course_docs",
      modules = "rendered/modules"
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check slides directory has revealjs format
  slides_quarto <- file.path(result$path, "rendered/slides/_quarto.yml")
  expect_true(file.exists(slides_quarto))
  slides_config <- yaml::read_yaml(slides_quarto)
  expect_equal(slides_config$format$revealjs$theme, "default")
  expect_true(slides_config$format$revealjs$`slide-number`)

  # Check assignments directory has HTML format
  assignments_quarto <- file.path(result$path, "rendered/assignments/_quarto.yml")
  expect_true(file.exists(assignments_quarto))
  assignments_config <- yaml::read_yaml(assignments_quarto)
  expect_equal(assignments_config$format$html$theme, "default")

  # Check course_docs directory has HTML format
  docs_quarto <- file.path(result$path, "rendered/course_docs/_quarto.yml")
  expect_true(file.exists(docs_quarto))
  docs_config <- yaml::read_yaml(docs_quarto)
  expect_equal(docs_config$format$html$theme, "default")

  # Check modules directory has HTML format
  modules_quarto <- file.path(result$path, "rendered/modules/_quarto.yml")
  expect_true(file.exists(modules_quarto))
  modules_config <- yaml::read_yaml(modules_quarto)
  expect_equal(modules_config$format$html$theme, "default")
})

test_that("presentation project generates revealjs _quarto.yml at root", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_presentation")

  result <- project_create(
    name = "test_presentation",
    location = project_path,
    type = "presentation",
    quarto = list(
      revealjs = list(
        theme = "sky",
        incremental = TRUE,
        slide_number = TRUE,
        transition = "fade"
      )
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check _quarto.yml at root has revealjs format
  quarto_path <- file.path(result$path, "_quarto.yml")
  expect_true(file.exists(quarto_path))
  quarto <- yaml::read_yaml(quarto_path)
  expect_equal(quarto$format$revealjs$theme, "sky")
  expect_true(quarto$format$revealjs$incremental)
  expect_true(quarto$format$revealjs$`slide-number`)
  expect_equal(quarto$format$revealjs$transition, "fade")
})

test_that("privacy sensitive project generates _quarto.yml in render directories", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_sensitive")

  result <- project_create(
    name = "test_sensitive",
    location = project_path,
    type = "project_sensitive",
    render_dirs = list(
      notebooks = "outputs/private/notebooks",
      docs = "outputs/private/docs"
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check _quarto.yml in notebooks render directory
  notebooks_quarto <- file.path(result$path, "outputs/private/notebooks/_quarto.yml")
  expect_true(file.exists(notebooks_quarto))
  notebooks_config <- yaml::read_yaml(notebooks_quarto)
  expect_equal(notebooks_config$format$html$theme, "default")

  # Check _quarto.yml in docs render directory
  docs_quarto <- file.path(result$path, "outputs/private/docs/_quarto.yml")
  expect_true(file.exists(docs_quarto))
  docs_config <- yaml::read_yaml(docs_quarto)
  expect_equal(docs_config$format$html$theme, "default")
})

test_that("project-specific quarto settings override global defaults", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_override")

  result <- project_create(
    name = "test_override",
    location = project_path,
    type = "project",
    quarto = list(
      html = list(
        embed_resources = FALSE,
        theme = "flatly",
        toc = FALSE,
        code_fold = TRUE,
        code_tools = TRUE
      )
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  quarto_path <- file.path(result$path, "_quarto.yml")
  expect_true(file.exists(quarto_path))

  quarto <- yaml::read_yaml(quarto_path)
  expect_equal(quarto$format$html$theme, "flatly")
  expect_false(quarto$format$html$toc)
  expect_true(quarto$format$html$`code-fold`)
  expect_true(quarto$format$html$`code-tools`)
  expect_false(quarto$format$html$`embed-resources`)
})

test_that("all _quarto.yml files have auto-generated headers", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_headers")

  result <- project_create(
    name = "test_headers",
    location = project_path,
    type = "course",
    render_dirs = list(
      slides = "rendered/slides",
      assignments = "rendered/assignments"
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Check root _quarto.yml header
  root_lines <- readLines(file.path(result$path, "_quarto.yml"))
  expect_true(any(grepl("Auto-generated by Framework", root_lines[1:5])))

  # Check slides _quarto.yml header
  slides_lines <- readLines(file.path(result$path, "rendered/slides/_quarto.yml"))
  expect_true(any(grepl("Auto-generated by Framework", slides_lines[1:5])))

  # Check assignments _quarto.yml header
  assignments_lines <- readLines(file.path(result$path, "rendered/assignments/_quarto.yml"))
  expect_true(any(grepl("Auto-generated by Framework", assignments_lines[1:5])))
})

test_that("format selection based on directory type", {
  skip_if_not_installed("yaml")
  skip_on_cran()

  test_root <- tempfile("framework_test_")
  dir.create(test_root)
  on.exit(unlink(test_root, recursive = TRUE), add = TRUE)

  project_path <- file.path(test_root, "test_formats")

  result <- project_create(
    name = "test_formats",
    location = project_path,
    type = "course",
    render_dirs = list(
      slides = "slides_output",        # Should be revealjs
      assignments = "assignments_out", # Should be HTML
      modules = "modules_out"          # Should be HTML
    ),
    git = list(use_git = FALSE)
  )

  expect_true(result$success)

  # Slides should use revealjs
  slides_config <- yaml::read_yaml(file.path(result$path, "slides_output/_quarto.yml"))
  expect_true("revealjs" %in% names(slides_config$format))
  expect_false("html" %in% names(slides_config$format))

  # Assignments should use HTML
  assignments_config <- yaml::read_yaml(file.path(result$path, "assignments_out/_quarto.yml"))
  expect_true("html" %in% names(assignments_config$format))
  expect_false("revealjs" %in% names(assignments_config$format))

  # Modules should use HTML
  modules_config <- yaml::read_yaml(file.path(result$path, "modules_out/_quarto.yml"))
  expect_true("html" %in% names(modules_config$format))
  expect_false("revealjs" %in% names(modules_config$format))
})
