default:
  project_type: project

  # Author information (used in notebooks, reports, etc.)
  author:
    name: "Your Name"
    email: "your.email@example.com"
    affiliation: "Your Institution"

  # Core directories (inline for discoverability)
  directories:
    notebooks: notebooks
    scripts: scripts
    functions: functions
    results_public: results/public
    results_private: results/private
    cache: data/cached
    scratch: data/scratch

  # Project options
  options:
    default_notebook_format: quarto  # quarto or rmarkdown
    renv_nag: true

  # Domain-specific settings (split files for scalability)
  data: settings/data.yml
  packages: settings/packages.yml
  connections: settings/connections.yml
  git: settings/git.yml
  security: settings/security.yml
