default:
  # Project metadata
  project_type: presentation  # Type: project, course, or presentation

  # Package dependencies - presentation focused (minimal)
  packages:
    - quarto
    - knitr

  # Project options
  options:
    # Directory paths (explicitly defined for discoverability)
    functions_dir: functions   # Helper functions

    data:
      cache_dir: data/cached   # Cached computation results

    # renv integration
    renv_nag: true  # Show reproducibility message on first scaffold()

  # Data catalog
  data:
    # Example: Uncomment and modify
    # example:
    #   path: data/example.csv
    #   type: csv
    #   locked: true
