default:
  # --------------------------------------------------------------------------
  # Project Metadata
  # --------------------------------------------------------------------------
  project_type: presentation  # Type: project, course, or presentation

  # --------------------------------------------------------------------------
  # Package Dependencies
  # --------------------------------------------------------------------------
  # Minimal packages for presentations
  # --------------------------------------------------------------------------
  packages:
    - quarto
    - knitr

  # --------------------------------------------------------------------------
  # Project Directories
  # --------------------------------------------------------------------------
  directories:
    functions: functions          # Helper functions
    cache: data/cached            # Cached computation results

  # --------------------------------------------------------------------------
  # Project Options
  # --------------------------------------------------------------------------
  options:
    renv_nag: true  # Show reproducibility message on first scaffold()

  # --------------------------------------------------------------------------
  # Data Catalog
  # --------------------------------------------------------------------------
  # Simple inline for most presentations
  # Large catalogs: use split file (data: settings/data.yml)
  # ⚠️ Main config ALWAYS wins over split files
  # --------------------------------------------------------------------------
  data:
    # Example: Uncomment and modify
    # example:
    #   path: data/example.csv
    #   type: csv
    #   locked: true
