default:
  # --------------------------------------------------------------------------
  # Project Metadata
  # --------------------------------------------------------------------------
  project_type: course  # Type: project, course, or presentation

  # --------------------------------------------------------------------------
  # Package Dependencies
  # --------------------------------------------------------------------------
  # Packages for teaching and course materials
  # --------------------------------------------------------------------------
  packages:
    - quarto
    - knitr
    - rmarkdown
    - dplyr

  # --------------------------------------------------------------------------
  # Project Directories
  # --------------------------------------------------------------------------
  directories:
    notebooks: notebooks              # Where make_notebook() creates files
    presentations: presentations      # Where presentation stubs go
    functions: functions              # Helper functions directory
    cache: data/cached                # Cached computation results

  # --------------------------------------------------------------------------
  # Project Options
  # --------------------------------------------------------------------------
  options:
    renv_nag: true  # Show reproducibility message on first scaffold()

  # --------------------------------------------------------------------------
  # Data Catalog
  # --------------------------------------------------------------------------
  # For complex data catalogs, use split file: data: settings/data.yml
  # --------------------------------------------------------------------------
  data:
    # Example: Uncomment and modify
    # example:
    #   path: data/example.csv
    #   type: csv
    #   locked: true

  # --------------------------------------------------------------------------
  # Database Connections
  # --------------------------------------------------------------------------
  # ⚠️ PRECEDENCE: Main config ALWAYS wins over split files
  # --------------------------------------------------------------------------
  connections:
    # Example: Uncomment and modify
    # db:
    #   driver: postgresql
    #   host: !expr Sys.getenv("DB_HOST")
    #   database: !expr Sys.getenv("DB_NAME")
    #   user: !expr Sys.getenv("DB_USER")
    #   password: !expr Sys.getenv("DB_PASS")

  # Security settings
  security:
    data_key: !expr Sys.getenv("DATA_ENCRYPTION_KEY", "")
