default:
  # Package dependencies - course/teaching focused
  packages:
    - quarto
    - knitr
    - rmarkdown
    - dplyr

  # Project options
  options:
    # Directory paths (defaults shown - customize as needed)
    functions_dir: functions           # Single dir or list: [functions, helpers]
    data:
      cache_dir: data/cached

    # renv integration
    renv_nag: true  # Show reproducibility message on first scaffold()

  # Data catalog
  data:
    # Example: Uncomment and modify
    # example:
    #   path: data/example.csv
    #   type: csv
    #   locked: true

  # Database connections
  connections:
    # Example: Uncomment and modify
    # db:
    #   driver: postgresql
    #   host: !expr Sys.getenv("DB_HOST")
    #   database: !expr Sys.getenv("DB_NAME")
    #   user: !expr Sys.getenv("DB_USER")
    #   password: !expr Sys.getenv("DB_PASS")

  # Security settings
  security:
    data_key: !expr Sys.getenv("DATA_ENCRYPTION_KEY", "")
