default:
  # --------------------------------------------------------------------------
  # Project Metadata
  # --------------------------------------------------------------------------
  project_type: presentation  # Type: project, course, or presentation

  # Presenter information (used in slides, handouts, etc.)
  author:
    name: "Your Name"
    email: "your.email@example.com"
    affiliation: "Your Institution"

  # --------------------------------------------------------------------------
  # Package Dependencies
  # --------------------------------------------------------------------------
  # Minimal packages for presentations
  # Use auto_attach: true to load automatically, false to install only
  # --------------------------------------------------------------------------
  packages:
    - name: ggplot2
      auto_attach: true
    - name: quarto
      auto_attach: false
    - name: knitr
      auto_attach: false

  # --------------------------------------------------------------------------
  # Project Directories
  # --------------------------------------------------------------------------
  directories:
    functions: functions          # Helper functions
    cache: data/cached            # Cached computation results

  # --------------------------------------------------------------------------
  # Project Behavior
  # --------------------------------------------------------------------------
  # Default notebook format for make_notebook() (quarto or rmarkdown)
  default_notebook_format: quarto

  # renv integration - show reproducibility message on first scaffold()
  renv_nag: true

  # --------------------------------------------------------------------------
  # Data Catalog
  # --------------------------------------------------------------------------
  # Simple inline for most presentations
  # Large catalogs: use split file (data: settings/data.yml)
  # ⚠️ Main config ALWAYS wins over split files
  # --------------------------------------------------------------------------
  data:
    # Example: Uncomment and modify
    # example:
    #   path: data/example.csv
    #   type: csv
    #   locked: true
