default:
  # --------------------------------------------------------------------------
  # Project Metadata
  # --------------------------------------------------------------------------
  project_type: project  # Type: project, course, or presentation

  # --------------------------------------------------------------------------
  # Package Dependencies
  # --------------------------------------------------------------------------
  # Packages to install and load during scaffold()
  # Use simple names or version pinning: dplyr@1.1.0, user/repo@branch
  # --------------------------------------------------------------------------
  packages:
    - dplyr
    - ggplot2
    - readr
    - tidyr

  # --------------------------------------------------------------------------
  # Project Directories
  # --------------------------------------------------------------------------
  # Define the core directory structure for your project.
  # Most users can leave these as defaults.
  # All paths are relative to the project root.
  # --------------------------------------------------------------------------
  directories:
    # Source code and notebooks
    notebooks: notebooks          # Where make_notebook() creates files
    scripts: scripts              # Where make_script() creates files
    functions: functions          # Single dir or list: [functions, helpers]

    # Analysis outputs
    results_public: results/public    # Shareable outputs (plots, reports)
    results_private: results/private  # Private outputs (internal reports)

    # Data and caching
    cache: data/cached            # Cached computation results
    scratch: data/scratch         # Temporary workspace

  # --------------------------------------------------------------------------
  # Project Options
  # --------------------------------------------------------------------------
  options:
    # renv integration - show reproducibility message on first scaffold()
    renv_nag: true

  # Data catalog
  data:
    # Example: Uncomment and modify
    # source:
    #   private:
    #     example:
    #       path: data/source/private/example.csv
    #       type: csv
    #       locked: true

  # Database connections
  connections:
    # Example: Uncomment and modify
    # db:
    #   driver: postgresql
    #   host: !expr Sys.getenv("DB_HOST")
    #   database: !expr Sys.getenv("DB_NAME")
    #   user: !expr Sys.getenv("DB_USER")
    #   password: !expr Sys.getenv("DB_PASS")

  # Security settings
  security:
    data_key: !expr Sys.getenv("DATA_ENCRYPTION_KEY", "")
    results_key: !expr Sys.getenv("RESULTS_ENCRYPTION_KEY", "")
