default:
  # Package dependencies
  packages:
    - name: dplyr
      auto_attach: true
    - name: ggplot2
      auto_attach: true
    - name: readr
      auto_attach: false

  # Project options
  options:
    # Directory paths (defaults shown - customize as needed)
    functions_dir: functions           # Single dir or list: [functions, helpers]
    results:
      public_dir: results/public
      private_dir: results/private
    data:
      cache_dir: data/cached
      scratch_dir: data/scratch

    # renv integration
    renv_nag: true  # Show reproducibility message on first scaffold()

  # Data catalog
  data:
    # Example: Uncomment and modify
    # source:
    #   private:
    #     example:
    #       path: data/source/private/example.csv
    #       type: csv
    #       locked: true

  # Database connections
  connections:
    # Example: Uncomment and modify
    # db:
    #   driver: postgresql
    #   host: !expr Sys.getenv("DB_HOST")
    #   database: !expr Sys.getenv("DB_NAME")
    #   user: !expr Sys.getenv("DB_USER")
    #   password: !expr Sys.getenv("DB_PASS")

  # Security settings
  security:
    data_key: !expr Sys.getenv("DATA_ENCRYPTION_KEY", "")
    results_key: !expr Sys.getenv("RESULTS_ENCRYPTION_KEY", "")
