default:
  # Project behavior
  default_notebook_format: quarto  # quarto or rmarkdown
  renv_nag: true

  data:
    - example: data/example.csv
  packages:
    - name: dplyr
      auto_attach: true
    - name: ggplot2
      auto_attach: true
  connections:
    framework:
      driver: "sqlite"
      database: "framework.db"
