default:
  data:
    - example: data/example.csv
  packages:
    - name: dplyr
      auto_attach: true
    - name: ggplot2
      auto_attach: true
  connections:
    framework:
      driver: "sqlite"
      database: "framework.db"
