name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            lintr
            rcmdcheck

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run lintr
        run: Rscript -e 'lintr::lint_package()'

      - name: Run testthat suite
        run: Rscript -e 'testthat::test_package("framework")'

      - name: R CMD check
        run: R CMD check . --no-manual --as-cran

      - name: Shellcheck scripts
        run: |
          shellcheck inst/bin/framework-global inst/bin/framework-shim inst/bin/install-cli.sh
